#include <cstdio>
#include <cstring>
#include <cstdint>

#include "main.h"
#include "iis3dwb_platform.h"
#include "iis3dwb_reg.h"

// Reference the USART2 handle generated by STM32CubeMX for USB Serial output
extern UART_HandleTypeDef huart2;

// Buffer for formatting UART debug strings
static char msg_buf[128];

// Helper function to send text strings over ST-Link Virtual COM Port (USART2)
static void uart_log(const char *str) {
    HAL_UART_Transmit(&huart2, (const uint8_t *)str, strlen(str), 100);
}

extern "C" void alt_main(void) {
    uint8_t whoamI = 0;
    uint8_t rst = 0;
    int16_t data_raw[3];
    float acceleration_mg[3];

    // Give hardware 50 ms to stabilize after power-on
    HAL_Delay(50);
    uart_log("\r\n--- Starting IIS3DWB Vibration Node ---\r\n");

    // 1. Link SPI function pointers into dev_ctx
    IIS3DWB_Init_Platform();

    // 2. Verify hardware communication via WHO_AM_I (Expected: 0x7B)
    iis3dwb_device_id_get(&dev_ctx, &whoamI);
    snprintf(msg_buf, sizeof(msg_buf), "WHO_AM_I Read: 0x%02X (Expected: 0x%02X)\r\n", whoamI, IIS3DWB_ID);
    uart_log(msg_buf);

    if (whoamI != IIS3DWB_ID) {
        uart_log("[ERROR] Sensor identity mismatch or SPI wiring failure! System halted.\r\n");
        while (1) {
            // Trap CPU here if sensor is unreachable
        }
    }
    uart_log("[OK] Sensor recognized successfully.\r\n");

    // 3. Perform a Software Reset
    iis3dwb_reset_set(&dev_ctx, PROPERTY_ENABLE);
    do {
        iis3dwb_reset_get(&dev_ctx, &rst);
    } while (rst); // Wait until the reset bit clears itself
    uart_log("[OK] Software reset complete.\r\n");

    // 4. Enable Block Data Update (BDU) to prevent reading fragmented MSB/LSB pairs
    iis3dwb_block_data_update_set(&dev_ctx, PROPERTY_ENABLE);

    // 5. Configure Full-Scale Range (+/- 4g)
    iis3dwb_xl_full_scale_set(&dev_ctx, IIS3DWB_4g);

    // 6. Set Output Data Rate to 26.67 kHz (Enables active sensing)
    iis3dwb_xl_data_rate_set(&dev_ctx, IIS3DWB_XL_ODR_26k7Hz);
    uart_log("[OK] Accelerometer configured at 26.67 kHz ODR (+/- 4g).\r\n");

    // 7. Main Acquisition Loop
    while (1) {
        uint8_t drdy = 0;

        // Check if fresh acceleration data is available
        iis3dwb_xl_flag_data_ready_get(&dev_ctx, &drdy);

        if (drdy) {
            // Read 6 consecutive bytes: X_L, X_H, Y_L, Y_H, Z_L, Z_H
            memset(data_raw, 0x00, 3 * sizeof(int16_t));
            iis3dwb_acceleration_raw_get(&dev_ctx, data_raw);

            // Convert raw 16-bit counts to milligravity (mg) using ST driver math
            acceleration_mg[0] = iis3dwb_from_fs4g_to_mg(data_raw[0]);
            acceleration_mg[1] = iis3dwb_from_fs4g_to_mg(data_raw[1]);
            acceleration_mg[2] = iis3dwb_from_fs4g_to_mg(data_raw[2]);

            // Stream CSV packet: X,Y,Z over UART for Python / Serial Monitor
            snprintf(msg_buf, sizeof(msg_buf), "%.2f,%.2f,%.2f\r\n",
                     acceleration_mg[0], acceleration_mg[1], acceleration_mg[2]);
            uart_log(msg_buf);

            // Small delay for testing/viewing on terminal (remove later for max throughput)
            HAL_Delay(50);
        }
    }
}
