#include "iis3dwb_platform.h"
#include "iis3dwb_reg.h"

// Reference the SPI1 handler generated by STM32CubeMX
extern SPI_HandleTypeDef hspi2;

// Global sensor driver context structure
stmdev_ctx_t dev_ctx;

// Define the Chip Select (CS) GPIO pin and port (Default: PA4)
#define IIS3DWB_CS_PORT GPIOA
#define IIS3DWB_CS_PIN  GPIO_PIN_4

int32_t platform_write(void *handle, uint8_t reg, const uint8_t *bufp, uint16_t len) {
    SPI_HandleTypeDef *spi = (SPI_HandleTypeDef *)handle;

    // Pull CS LOW to start SPI transmission
    HAL_GPIO_WritePin(IIS3DWB_CS_PORT, IIS3DWB_CS_PIN, GPIO_PIN_RESET);

    // Bit 7 = 0 indicates a Write operation
    uint8_t reg_addr = reg & 0x7F;
    if (HAL_SPI_Transmit(spi, &reg_addr, 1, 100) != HAL_OK) {
        HAL_GPIO_WritePin(IIS3DWB_CS_PORT, IIS3DWB_CS_PIN, GPIO_PIN_SET);
        return -1;
    }

    if (HAL_SPI_Transmit(spi, (uint8_t *)bufp, len, 100) != HAL_OK) {
        HAL_GPIO_WritePin(IIS3DWB_CS_PORT, IIS3DWB_CS_PIN, GPIO_PIN_SET);
        return -1;
    }

    // Pull CS HIGH to end SPI transmission
    HAL_GPIO_WritePin(IIS3DWB_CS_PORT, IIS3DWB_CS_PIN, GPIO_PIN_SET);
    return 0;
}

int32_t platform_read(void *handle, uint8_t reg, uint8_t *bufp, uint16_t len) {
    SPI_HandleTypeDef *spi = (SPI_HandleTypeDef *)handle;

    // Pull CS LOW to start SPI transmission
    HAL_GPIO_WritePin(IIS3DWB_CS_PORT, IIS3DWB_CS_PIN, GPIO_PIN_RESET);

    // Bit 7 = 1 indicates a Read operation
    uint8_t reg_addr = reg | 0x80;
    if (HAL_SPI_Transmit(spi, &reg_addr, 1, 100) != HAL_OK) {
        HAL_GPIO_WritePin(IIS3DWB_CS_PORT, IIS3DWB_CS_PIN, GPIO_PIN_SET);
        return -1;
    }

    if (HAL_SPI_Receive(spi, bufp, len, 100) != HAL_OK) {
        HAL_GPIO_WritePin(IIS3DWB_CS_PORT, IIS3DWB_CS_PIN, GPIO_PIN_SET);
        return -1;
    }

    // Pull CS HIGH to end SPI transmission
    HAL_GPIO_WritePin(IIS3DWB_CS_PORT, IIS3DWB_CS_PIN, GPIO_PIN_SET);
    return 0;
}

void IIS3DWB_Init_Platform(void) {
    // Connect SPI hardware handle and function pointers to the ST context
    dev_ctx.write_reg = platform_write;
    dev_ctx.read_reg  = platform_read;
    dev_ctx.handle    = &hspi2;
}
